apiVersion: v1
kind: PersistentVolume
metadata:
  name: "prowlarr-config"
  labels:
    type: "local"
spec:
  storageClassName: "local-path"  
  capacity:
    storage: "200Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/prowlarr"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: default
spec:
  storageClassName: "local-path"
  volumeName: prowlarr-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "200Mi"
