apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - raspberrypi-worker-1
      containers:
        - name: qbittorrent
          image: qbittorrentofficial/qbittorrent-nox:5.0.3-1
          ports:
            - name: webui
              containerPort: 8080
            - name: bittorrent-tcp
              containerPort: 6881
              protocol: TCP
            - name: bittorrent-udp
              containerPort: 6881
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          env:
            - name: QBT_WEBUI_PORT
              value: "30202"
            - name: UMASK
              value: "002"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: downloads
          hostPath:
            path: /mnt/dock2/Downloads

---

apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: default
spec:
  selector:
    app: qbittorrent
  ports:
    - name: webui
      protocol: TCP
      port: 30202
      nodePort: 30202 # this has to match the QBT_WEBUI_PORT env variable
    - name: bittorrent-tcp
      protocol: TCP
      port: 6881
      nodePort: 30298
    - name: bittorrent-udp
      protocol: UDP
      port: 6881
      nodePort: 30299
  type: NodePort
