apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: qbittorrentofficial/qbittorrent-nox:5.0.3-1
          ports:
            - name: webui
              containerPort: 8080
            - name: bittorrent-tcp
              containerPort: 6881
              protocol: TCP
            - name: bittorrent-udp
              containerPort: 6881
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          env:
            - name: QBT_WEBUI_PORT
              value: "30413"
            - name: UMASK
              value: "002"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: downloads
          persistentVolumeClaim:
            claimName: plex-data

---

apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: default
spec:
  selector:
    app: qbittorrent
  ports:
    - name: webui
      protocol: TCP
      port: 30413
      nodePort: 30413 # this has to match the QBT_WEBUI_PORT env variable
    - name: bittorrent-tcp
      protocol: TCP
      port: 6881
      nodePort: 30423
    - name: bittorrent-udp
      protocol: UDP
      port: 6881
      nodePort: 30433
  type: NodePort
