apiVersion: v1
kind: PersistentVolume
metadata:
  name: "qbittorrent-config"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "200Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/qbittorrent-config"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "200Mi"
