apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-https
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home.mancuso.services`) || Path(`/home`)
      kind: Rule
      services:
        - name: home-assistant
          port: 8123
      #middlewares:
      #  - name: sso
      #    namespace: default
  tls: {}

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-http
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`home.mancuso.services`) || Path(`/home`)
      kind: Rule
      priority: 10
      services:
        - name: home-assistant
          port: 8123
      middlewares:
        - name: redirect-https
          namespace: default
