---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "home-assistant"
  namespace: "home-assistant"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/home-assistant"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "home-assistant"
  name: "home-assistant"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
---