apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home.mancuso.services
  namespace: home-assistant
spec:
  secretName: home.mancuso.services-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: home.mancuso.services
  dnsNames:
  - home.mancuso.services