apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole.mancuso.services
  #namespace: cert-manager
spec:
  secretName: pihole.mancuso.services-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pihole.mancuso.services
  dnsNames:
  - pihole.mancuso.services