apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`whoami.mancuso.services`)
      kind: Rule
      priority: 10
      services:
        - name: whoami
          port: 80
