apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-https
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`whoami.mancuso.services`) || Path(`/whoami`)
      services:
        - name: whoami
          port: 80
  tls: {}

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-http
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`whoami.mancuso.services`) || Path(`/whoami`)
      services:
        - name: whoami
          port: 80
      middlewares:
        - name: redirect-https
  