apiVersion: v1
kind: PersistentVolume
metadata:
  name: "qbittorrent-config"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "600Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/qbittorrent-config"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: qbittorrent
  name: "qbittorrent-config"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi