image:
  # -- image repository
  repository: ghcr.io/k8s-at-home/qbittorrent
  # -- image tag
  tag: v4.3.7
  # -- image pull policy
  pullPolicy: IfNotPresent

settings:
  # -- Enables automatic port configuration at startup
  # This sets the qbittorrent port to the value of `service.bittorrent.ports.bittorrent.port`.
  automaticPortSetup: false

# -- environment variables. See [image docs](https://docs.k8s-at-home.com/our-container-images/configuration/) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    existingClaim:  # your-claim
    mountPath: /media

  media:
    enabled: false
    mountPath: /media

  downloads:
    enabled: false
    existingClaim: plex-data
    mountPath: /downloads

