apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-letsencrypt-issuer
  namespace: default
spec:
  encryptedData:
    private-key: AgCJsqPKKOv95YcO6QRv8Q7E6up56rtPtAgnSXTvTAxaeQqLZE0fSPnOyDNO2VCXd7vPxooncPeQhEBUkTR57mLBs5KJ9fHO9kMvvCqShHOCnNTvomkBSdIIGt0WWqUwotoaIC03q8G+LCyy/Knh+dHMtjDRdkEcKoV7CwyWCoVVYRgaikyu+CmbCb9bmksOllR7L9Cy3QhpRvJx0LsVTpu/kDXZMoNqiTOnQBG7wp/YCkXqrMI2LWfU8JU6xu2JeNX7M7IeW8kMe0PyY6AqV/nYZvTd9AR+/jfhqwtuMglvv7CmZVVDueoTgOv/wZ3EJFLrH0llgyJI/hJAWpdArAsOegjzlhAsHfsM7afos+HoqwOUYRhSGImUhhlQqieeSSdSBixBvPSA0VbOjLAKPlH7Ob8OVSdeneGLFtcujkVWyzKD0M021ToNcLlstr/3JSfUjp/WQUSxOewe6WEiLRu8z1vmb3alt8FmMDJCmfYFiXjaVF9lgpCsrgbd2LwknzlN9di8d+6SnROHi1ZZ5DSGxfIJXMhiiqnNo5j/g7KPcRKKbX1k2Hh/YbVUD9DTQ0YcCFbl9pddWySrZS4vJvMiHJMvTO1H7mnmRvq5wqSDuLeOcuR3Emk6L4kQoRukB7YOboe9ZaQ5WDOo+Y62wL7SetFLhNRw7flSLtDQCsgobGCYtYNDUGbgJJogERb6zdZ2Xa/K
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cert-manager-letsencrypt-issuer
      namespace: default

