apiVersion: v1
kind: PersistentVolume
metadata:
  name: "sonarr-config"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "200Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/sonarr"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: default
spec:
  volumeName: sonarr-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "200Mi"
