apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mancuso.services
  namespace: cert-manager
spec:
  secretName: mancuso.services-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mancuso.services
  dnsNames:
  - "*.mancuso.services"