apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    app: plex
  annotations:
spec:
  type: LoadBalancer
  ports:
  - port: 32400
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 32400
  selector:
    app: plex

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      # serviceAccountName: default
      # automountServiceAccountToken: true
      # dnsPolicy: ClusterFirst
      # enableServiceLinks: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - raspberrypi-worker-1
      containers:
        - name: plex
          #image: "linuxserver/plex:1.32.6"
          #image: "ghcr.io/onedr0p/plex:1.32.5.7516-8f4248874"
          image: "greensheep/plex-server-docker-rpi"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: UTC
          ports:
            - name: http
              containerPort: 32400
              protocol: TCP
          # livenessProbe:
          #   tcpSocket:
          #     port: 32400
          #   initialDelaySeconds: 0
          #   failureThreshold: 3
          #   timeoutSeconds: 1
          #   periodSeconds: 10
          # readinessProbe:
          #   tcpSocket:
          #     port: 32400
          #   initialDelaySeconds: 0
          #   failureThreshold: 3
          #   timeoutSeconds: 1
          #   periodSeconds: 10
          # startupProbe:
          #   tcpSocket:
          #     port: 32400
          #   initialDelaySeconds: 0
          #   failureThreshold: 30
          #   timeoutSeconds: 1
          #   periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: "/config"
            - name: data
              mountPath: /data
              readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config
        - name: data
          persistentVolumeClaim:
            claimName: plex-data