apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    app: plex
  annotations:
spec:
  type: NodePort
  ports:
  - port: 32400
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 30201
  selector:
    app: plex

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - raspberrypi-worker-1
      containers:
        - name: plex
          image: "greensheep/plex-server-docker-rpi"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: UTC
          ports:
            - name: http
              containerPort: 32400
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/config"
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config
        - name: data
          hostPath:
            path: /mnt/dock2/