apiVersion: v1
kind: PersistentVolume
metadata:
  name: "plex-config"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "600Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/plex-config"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex
  name: "plex-config"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "plex-data"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "1000Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/dock2"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex
  name: "plex-data"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
