apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana.mancuso.services
  #namespace: cert-manager
spec:
  secretName: grafana.mancuso.services-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: grafana.mancuso.services
  dnsNames:
  - grafana.mancuso.services